# Generated by Django 2.0.6 on 2018-06-08 19:47

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='date_joined',
            field=models.DateTimeField(default=datetime.datetime(2018, 6, 8, 19, 47, 8, 773971, tzinfo=utc)),
        ),
    ]
