# Generated by Django 2.0.2 on 2018-06-03 13:16

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='date_joined',
            field=models.DateTimeField(default=datetime.datetime(2018, 6, 3, 13, 16, 42, 386472, tzinfo=utc)),
        ),
        migrations.AlterModelTable(
            name='user',
            table='users',
        ),
    ]
