# Generated by Django 2.0.6 on 2018-06-08 19:51

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20180608_1947'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='date_joined',
            field=models.DateTimeField(default=datetime.datetime(2018, 6, 8, 19, 51, 33, 155178, tzinfo=utc)),
        ),
    ]
