# Generated by Django 2.0.6 on 2018-06-08 20:59

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20180608_1951'),
    ]

    operations = [
        migrations.RenameField(
            model_name='dicomnode',
            old_name='peer_url',
            new_name='remote_url',
        ),
        migrations.AlterField(
            model_name='user',
            name='date_joined',
            field=models.DateTimeField(default=datetime.datetime(2018, 6, 8, 20, 59, 31, 663705, tzinfo=utc)),
        ),
    ]
