# Generated by Django 2.0.2 on 2018-02-21 13:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20180221_1338'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='study',
            name='referring_physician',
        ),
    ]
