# Generated by Django 2.0.2 on 2018-04-07 19:16

import apps.core.models
from django.db import migrations, models
import jsonfield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_study_study_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProcessingResult',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('expire_date', models.DateTimeField()),
                ('image', models.FileField(blank=True, null=True, upload_to=apps.core.models.processed_image_path, verbose_name='Image')),
                ('json', jsonfield.fields.JSONField(verbose_name='JSON')),
                ('session_token', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'processing_results',
            },
        ),
        migrations.AddField(
            model_name='dicomnode',
            name='protocol',
            field=models.CharField(default='DICOMWEB', max_length=20, verbose_name='Protocol Type'),
        ),
    ]
