# Generated by Django 2.0.2 on 2018-04-15 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_auto_20180414_0108'),
    ]

    operations = [
        migrations.AddField(
            model_name='plugin',
            name='is_installed',
            field=models.BooleanField(default=False, verbose_name='Is installed'),
        ),
    ]
