# Generated by Django 2.0.2 on 2018-05-03 20:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_plugin_is_installed'),
    ]

    operations = [
        migrations.AddField(
            model_name='plugin',
            name='is_native',
            field=models.BooleanField(default=False, verbose_name='Is native'),
        ),
        migrations.AddField(
            model_name='plugin',
            name='is_package_manageable',
            field=models.BooleanField(default=False, verbose_name='Is package manageable'),
        ),
    ]
