# Generated by Django 2.0.2 on 2018-05-10 20:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_auto_20180503_2005'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='plugin',
            name='is_native',
        ),
        migrations.RemoveField(
            model_name='plugin',
            name='is_package_manageable',
        ),
        migrations.AlterField(
            model_name='plugin',
            name='name',
            field=models.CharField(max_length=100, unique=True, verbose_name='Name'),
        ),
    ]
